//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DooSan.BrandCenter.BrandCenterDBConext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BrandCenterEntities : DbContext
    {
        public BrandCenterEntities()
            : base("name=BrandCenterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblGroup> tblGroup { get; set; }
        public virtual DbSet<tblGroupUser> tblGroupUser { get; set; }
        public virtual DbSet<tblCodeMaster> tblCodeMaster { get; set; }
        public virtual DbSet<tblDepartmentBuyer> tblDepartmentBuyer { get; set; }
        public virtual DbSet<tblFiles> tblFiles { get; set; }
        public virtual DbSet<tblGroupMenu> tblGroupMenu { get; set; }
        public virtual DbSet<tblLogging> tblLogging { get; set; }
        public virtual DbSet<tblLoginHistory> tblLoginHistory { get; set; }
        public virtual DbSet<tblMenu> tblMenu { get; set; }
        public virtual DbSet<tb_Company> tb_Company { get; set; }
        public virtual DbSet<tb_Dept> tb_Dept { get; set; }
        public virtual DbSet<tb_Duty> tb_Duty { get; set; }
        public virtual DbSet<tb_Rank> tb_Rank { get; set; }
        public virtual DbSet<tb_User> tb_User { get; set; }
        public virtual DbSet<tb_UserLang> tb_UserLang { get; set; }
        public virtual DbSet<tblButton> tblButtons { get; set; }
        public virtual DbSet<tblGroupButton> tblGroupButtons { get; set; }
        public virtual DbSet<tb_AdditionalJob> tb_AdditionalJob { get; set; }
        public virtual DbSet<TB_DEPT_EX> TB_DEPT_EX { get; set; }
        public virtual DbSet<tb_DeptLang> tb_DeptLang { get; set; }
        public virtual DbSet<TB_USER_EX> TB_USER_EX { get; set; }
    
        public virtual ObjectResult<SP_ADM_sGROUPMASTERTestPG_Result> SP_ADM_sGROUPMASTERTestPG(string gROUPNAME, Nullable<int> cURRENTPAGE, Nullable<int> pAGE_COUNT)
        {
            var gROUPNAMEParameter = gROUPNAME != null ?
                new ObjectParameter("GROUPNAME", gROUPNAME) :
                new ObjectParameter("GROUPNAME", typeof(string));
    
            var cURRENTPAGEParameter = cURRENTPAGE.HasValue ?
                new ObjectParameter("CURRENTPAGE", cURRENTPAGE) :
                new ObjectParameter("CURRENTPAGE", typeof(int));
    
            var pAGE_COUNTParameter = pAGE_COUNT.HasValue ?
                new ObjectParameter("PAGE_COUNT", pAGE_COUNT) :
                new ObjectParameter("PAGE_COUNT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ADM_sGROUPMASTERTestPG_Result>("SP_ADM_sGROUPMASTERTestPG", gROUPNAMEParameter, cURRENTPAGEParameter, pAGE_COUNTParameter);
        }
    
        public virtual ObjectResult<SP_ADM_sGROUPUSER_Result> SP_ADM_sGROUPUSER(string gROUPID)
        {
            var gROUPIDParameter = gROUPID != null ?
                new ObjectParameter("GROUPID", gROUPID) :
                new ObjectParameter("GROUPID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ADM_sGROUPUSER_Result>("SP_ADM_sGROUPUSER", gROUPIDParameter);
        }
    }
}
