//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DooSan.BrandCenter.BrandCenterDBConext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_AdditionalJob
    {
        public string LoginID { get; set; }
        public string TypeCode { get; set; }
        public string SeqNo { get; set; }
        public string DeptCode { get; set; }
        public string RankCode { get; set; }
        public string DutyCode { get; set; }
        public string DutyType { get; set; }
        public string SubJobCode { get; set; }
        public string Add_Ent_Code { get; set; }
        public string Interface { get; set; }
        public string DisplayYN { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string DutyName { get; set; }
        public string RankName { get; set; }
        public string Stamp { get; set; }
        public string ExpDate { get; set; }
    }
}
