//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DooSan.BrandCenter.BrandCenterDBConext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_DEPT_EX
    {
        public string DEPTCODE { get; set; }
        public string BGCODE { get; set; }
        public string RECEIPT_UNIT_CODE { get; set; }
        public string APPROVAL_UNIT_CODE { get; set; }
        public string RECEIVABLE { get; set; }
        public string APPROVABLE { get; set; }
        public string FC_TARGET_YN { get; set; }
        public string ORG_VIEW { get; set; }
        public string UNIT_FULL_CODE { get; set; }
        public string UNIT_FULL_NAME { get; set; }
        public string ENG_UNIT_NAME { get; set; }
        public string SHORT_NAME { get; set; }
        public string DSCR { get; set; }
        public string SIMPLENM { get; set; }
    }
}
