//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DooSan.BrandCenter.BrandCenterDBConext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_User
    {
        public string EmpID { get; set; }
        public string CurrentEmpID { get; set; }
        public string LoginID { get; set; }
        public string EMail { get; set; }
        public string CompanyCode { get; set; }
        public string MainDeptCode { get; set; }
        public string CreatedDT { get; set; }
        public string EndDate { get; set; }
        public string DisplayName { get; set; }
        public string DisplayYN { get; set; }
        public string DutyCode { get; set; }
        public string JobCode { get; set; }
        public string RankCode { get; set; }
        public string FaxNumber { get; set; }
        public string HomePhone { get; set; }
        public string CellPhone { get; set; }
        public string ExtensionNumber { get; set; }
        public string Sort { get; set; }
        public string Interface { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string ObjectDetailCategory { get; set; }
        public string ObjectCategory { get; set; }
        public string Person_ID { get; set; }
        public string ExtensionNumber2 { get; set; }
        public string DooDreamYN { get; set; }
        public string etcUser { get; set; }
        public string classify { get; set; }
        public string JOB_FULL_NM { get; set; }
        public string EMP_TYPE { get; set; }
        public string MyLang { get; set; }
        public string Location { get; set; }
        public string JOB_DETAIL { get; set; }
        public string HIDE_YellowPage_YN { get; set; }
        public string DOC_CHECK_YN { get; set; }
        public Nullable<int> Ver { get; set; }
        public string PersonnelAreaCode { get; set; }
        public string OrgUnitID { get; set; }
        public string DoopisDeptCode { get; set; }
    }
}
