//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DooSan.BrandCenter.BrandCenterDBConext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_USER_EX
    {
        public string LOGINID { get; set; }
        public string LOCK { get; set; }
        public string DEPUTY_YN { get; set; }
        public Nullable<System.DateTime> DEPUTY_FROM_DT { get; set; }
        public Nullable<System.DateTime> DEPUTY_TO_DT { get; set; }
        public string DEPUTY_CODE { get; set; }
        public string DEPUTY_NAME { get; set; }
        public string APPROVAL_ARRIVAL_YN { get; set; }
        public string APPROVAL_ARRIVAL_MEDIUM { get; set; }
        public string APPROVAL_COMPLETE_YN { get; set; }
        public string APPROVAL_COMPLETE_MEDIUM { get; set; }
        public string APPROVAL_REVIEW_YN { get; set; }
        public string APPROVAL_REVIEW_MEDIUM { get; set; }
        public string APPROVAL_UNIT_CODE { get; set; }
        public string RECEIPT_UNIT_CODE { get; set; }
        public string APPROVER_CODE { get; set; }
        public string MESSENGER_USAGE_STAT { get; set; }
        public string EDITER_MEDIUM { get; set; }
        public string FILE_ATTACH_MEDIUM { get; set; }
        public string ORG_LANGUAGE { get; set; }
        public string ORG_VIEW { get; set; }
        public string FC_TARGET_YN { get; set; }
        public string ABSENT_REASON { get; set; }
        public string APPROVAL_DEFAULT_FORM_YN { get; set; }
        public string APPROVAL_DEFAULT_FORM_ID { get; set; }
        public string DISPLAY_NAME { get; set; }
        public string DISPLAY_ENG_NAME { get; set; }
        public string DISPLAY_MAIL_SENDER_NAME { get; set; }
    }
}
