//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DooSan.BrandCenter.BrandCenterDBConext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_BOARD_COMMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_BOARD_COMMENT()
        {
            this.TBL_BOARD_COMMENT_LIKE = new HashSet<TBL_BOARD_COMMENT_LIKE>();
        }
    
        public int COMMENT_IDX { get; set; }
        public string COMMENT { get; set; }
        public Nullable<System.DateTime> COMMENT_DATE { get; set; }
        public Nullable<int> COMMENT_GROUP { get; set; }
        public Nullable<int> COMMENT_ORDER { get; set; }
        public string INPUT_USER { get; set; }
        public Nullable<System.DateTime> INPUT_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> BOARD_IDX { get; set; }
    
        public virtual TBL_BOARD TBL_BOARD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_BOARD_COMMENT_LIKE> TBL_BOARD_COMMENT_LIKE { get; set; }
    }
}
