//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DooSan.BrandCenter.BrandCenterDBConext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFiles
    {
        public int LINKIDX { get; set; }
        public string TYPE { get; set; }
        public int IDX { get; set; }
        public string URLPATH { get; set; }
        public string PYSICALPATH { get; set; }
        public string ORI_FILENAME { get; set; }
        public bool IS_BOARD { get; set; }
        public string SIZE { get; set; }
        public string EXTENSION { get; set; }
        public string INPUT_USER { get; set; }
        public Nullable<System.DateTime> INPUT_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    }
}
