//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DooSan.BrandCenter.BrandCenterDBConext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMenu
    {
        public string MENUID { get; set; }
        public string MENUNAME { get; set; }
        public string DESC { get; set; }
        public Nullable<int> LEVEL { get; set; }
        public Nullable<int> SORT { get; set; }
        public Nullable<bool> USE_YN { get; set; }
        public Nullable<bool> DEFAULT_YN { get; set; }
        public Nullable<bool> TEAM_YN { get; set; }
        public string TYPE { get; set; }
        public string PARENT_MENUID { get; set; }
        public string URL { get; set; }
        public string INPUT_USER { get; set; }
        public Nullable<System.DateTime> INPUT_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    }
}
