//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DooSan.BrandCenter.BrandCenterDBConext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPreset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPreset()
        {
            this.tblPresetTextBox = new HashSet<tblPresetTextBox>();
        }
    
        public int Preset_Idx { get; set; }
        public string TypeCode { get; set; }
        public string SizeCode { get; set; }
        public string CaseText { get; set; }
        public string PositionValue { get; set; }
        public Nullable<int> DefaultHeight { get; set; }
        public Nullable<int> DefaultWidth { get; set; }
        public Nullable<int> MaxHeight { get; set; }
        public Nullable<int> MaxWidth { get; set; }
        public Nullable<int> ImageFileIdx { get; set; }
        public Nullable<bool> IsHeaderExist { get; set; }
        public Nullable<int> HeadLineCount { get; set; }
        public Nullable<bool> IsFooterExist { get; set; }
        public string INPUT_USER { get; set; }
        public Nullable<System.DateTime> INPUT_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> PresetText_Idx { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPresetTextBox> tblPresetTextBox { get; set; }
    }
}
